### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by alaminzju** [SONGDONGYUAN1994/PseudotimeDE#1]
Hi,
I am getting the following error when trying to install PseudotimeDE:
> install_github("SONGDONGYUAN1994/PseudotimeDE")
Error: Failed to install 'unknown package' from GitHub:
  Send failure: Connection was reset
I have used RStudio (Version 1.3.1073) and R-4.0.3. Please see this and give your suggestions.

**Comment by alaminzju** [comment]
The following code solve my problem.
install.packages("remotes")
remotes::install_github("SONGDONGYUAN1994/PseudotimeDE")

**Comment by SONGDONGYUAN1994** [comment]
I have changed the vignette. Thanks!
