### ISSUE TITLE
Calculating mean fold-change

### ISSUE THREAD

**Issue by e1992** [SONGDONGYUAN1994/PseudotimeDE#13]
Hi  Dongyuan, 

Another question for you, does runPseudotimeDE calculate the mean fold change in gene expression over pseudotime? I can't see it anywhere in the code so I'm guessing it doesn't. Is there a simple way I can calculate this from the output? I'd like to filter genes by fold-change. 

Thanks!

**Comment by SONGDONGYUAN1994** [comment]
Hi,
This question is a little bit tricky. The estimates of PseduotimeDE is a curve; how would you define the "mean fold change"? If you have a clear definition based on the estimated curve $\hat{f}$, then you can calculate it by using the fitted gam models `res$gam.fit`.  `predict(res$gam.fit[[1]])` should give you the mean expression values of gene 1 along the pseudotime.

**Comment by e1992** [comment]
That works, thank you! I used the difference between the min and max from predict(). I'm defining it as the fold change in mean expression along pseudotime, so thats perfect. Thanks.

**Comment by SONGDONGYUAN1994** [comment]
Sounds great! I may consider adding this into the output. Thanks!
