### ISSUE TITLE
NAs in runPseudotimeDE if no Assay named 'RNA'

### ISSUE THREAD

**Issue by j-uncc** [SONGDONGYUAN1994/PseudotimeDE#19]
Hello and thank you for creating this package,

The seurat object I am using for runPseudotimeDE does not have an assay named 'RNA'. This is not an issue for the pseudotimeDE function, but when I run runPseudotimeDE, the result is all NAs (implying that an error occurs during the pseudotimeDE tryCatch).

Looking at the runPseudotimeDE function code, the tryCatch expression does not include the user-inputted seurat.assay parameter. It only sets the parameter after the tryCatch runs successfully. If there is no suerat.assay named 'RNA', then the tryCatch will give an error and return all NAs, even if the user supplies an alternate seurat.assay.

I confirmed this by running the runPseudotimeDE function with no other changes than including 'seurat.assay = seurat.assay,' in the tryCatch expr. and it outputs the tibble object with non-NA values as expected.

To reproduce this, use runPseudotimeDE with a seurat object that has no assay object named 'RNA' and supply an alternate value for seeurat.assay. I will be happy to share my code via email if necessary. Thank you.

Here is the altered portion of the function that worked for me:

  res <- BiocParallel::bplapply(gene.vec, function(x, ...) {
    cur_res <- tryCatch(expr = pseudotimeDE(gene = x,
                                            ori.tbl = ori.tbl,
                                            sub.tbl = sub.tbl,
                                            mat = mat[x,],
                                            model = model,
                                            seurat.assay = seurat.assay), #note that the seurat.assay has been moved here #input only the target gene
                        error = function(e) {
                          list(fix.pv = NA,
                               emp.pv = NA,
                               para.pv = NA,
                               ad.pv = NA,
                               rank = NA,
                               gam.fit = NA,
                               zinf = NA,
                               aic = NA,
                               expv.quantile = NA,
                               expv.mean = NA,
                               expv.zero = NA)
                        })
    cur_res
  },
  assay.use = assay.use,
  k = k,
  knots = knots,
  fix.weight = fix.weight,
  aicdiff = aicdiff,
  quant = quant,
  usebam = usebam, #and the seurat.assay has been removed from here
  BPPARAM = BPPARAM)

**Comment by SONGDONGYUAN1994** [comment]
Hi J,
Thanks for reporting this bug! I have updated the package based on your code. Could you please double-check if it works now?

Best,
Dongyuan
