### ISSUE TITLE
Test statistic s in output of runPseudotimeDE

### ISSUE THREAD

**Issue by simonmfr** [SONGDONGYUAN1994/PseudotimeDE#20]
Hi, I wonder if the per-gene test statistic s<sub>j</sub> is included in the output of runPseudotimeDE? Or alternatively, is there a way to extract it?
Thank you.
Simon

**Comment by SONGDONGYUAN1994** [comment]
@simonmfr Hi Simon,
I have updated the package and now the output contains 1 new value: `test.statistics`. Please let me know if it works for you now, thanks!

Best,
Dongyuan

**Comment by simonmfr** [comment]
It works, much appreciated!
