### ISSUE TITLE
Are there any alternatives of the function prcomp to get the first two PCs

### ISSUE THREAD

**Issue by BW15061999** [SONGDONGYUAN1994/PseudotimeDE#3]
It's too time-consuming to use _prcomp_ in every subsamples, are there any alternatives or solutions? Thanks

**Comment by SONGDONGYUAN1994** [comment]
Hi,
Yes, there is. To clarify, our tutorial only gives an example of how to get the estimate of the original sample and subsamples. You can adjust the procedure based on your need. The only requirement is that the procedure should be the same for the original sample and subsamples.

For your problem, you can use the R package irlba (https://rdrr.io/cran/irlba/man/prcomp_irlba.html). This is much faster than prcomp. Thanks!
